# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 04:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('head', models.ImageField(blank=True, default='cute.jpg', upload_to='head')),
                ('password', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_mem1', to=settings.AUTH_USER_MODEL)),
                ('self_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_mem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_mem2', to=settings.AUTH_USER_MODEL)),
                ('fans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_mem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/%Y/%m')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('sub_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('col_num', models.PositiveIntegerField(default=0)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_work', models.ManyToManyField(related_name='work_tag', to='picture.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='works_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Works'),
        ),
    ]
