# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=picture.models.user_directory_path),
        ),
    ]
